version: '3.8'

services:  
  server:
    image: alphacep/kaldi-vosk-model-ru:latest
    build: server
    network_mode: "host"
    deploy:
      mode: replicated
      replicas: 1
  updater:
    build: update_server
    network_mode: "host"
    volumes:
      - ../:/server/model
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=Europe/Moscow
      - PORT=8084