version: '3.8'

services:
  server_z:
    image: alphacep/kaldi-vosk-model-ru:latest
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    build: server
    restart: always
    network_mode: "host"
    volumes:
      - ./model_files/corpus:/opt/vosk-model-ru/model/new/data/corpus
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=Europe/Moscow
  updater:
    build: update_server
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    network_mode: "host"
    volumes:
      - ./model_files:/server/model_files
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=Europe/Moscow
      - PORT=8084
